export const topSixMainCoins = ['USDT', 'USDC', 'SOL', 'CNTRY', 'BTC', 'ETH'];

// base, quote

export const tableMainValuesFromApi = [
  {
    pairId: 11,
    name: 'ETH/USDT',
    quoteCurrency: 'USDT',
    check: false,
    BaseCurrency: 'ETH',
    pairImg: './Ethereum(ETH).png',
    pairPrice: '0.000356',
    pairChange: '+1.81%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 12,
    name: 'AVAX/USDT',
    quoteCurrency: 'USDT',
    check: false,
    BaseCurrency: 'AVAX',
    pairImg: './Avalanche(AVAX).png',
    pairPrice: '0.000007732',
    pairChange: '-6.85%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 13,
    name: 'LRC/USDT',
    quoteCurrency: 'USDT',
    check: false,
    BaseCurrency: 'LRC',
    pairImg: './Loopring(LRC).png',
    pairPrice: '0.00002928763',
    pairChange: '-6.77%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 14,
    name: 'CHIB/USDT',
    quoteCurrency: 'USDT',
    check: false,
    BaseCurrency: 'CHIB',
    pairImg: './SHIBAINU(SHIB).png',
    pairPrice: '0.00002073',
    pairChange: '+4.65%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 15,
    name: 'ADA/USDT',
    quoteCurrency: 'USDT',
    check: false,
    BaseCurrency: 'ADA',
    pairImg: './DerivaDAO(DDX).png',
    pairPrice: '0.0098774',
    pairChange: '-4.41%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 16,
    name: 'ROSE/USDT',
    quoteCurrency: 'USDT',
    check: false,
    BaseCurrency: 'ROSE',
    pairImg: './Rise(Rise).png',
    pairPrice: '0.000120984',
    pairChange: '-7.13%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 111,
    name: 'ETH/SRM',
    quoteCurrency: 'SRM',
    check: false,
    BaseCurrency: 'ETH',
    pairImg: './Ethereum(ETH).png',
    pairPrice: '0.000356',
    pairChange: '+1.81%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 112,
    name: 'AVAX/SRM',
    quoteCurrency: 'SRM',
    check: false,
    BaseCurrency: 'AVAX',
    pairImg: './Avalanche(AVAX).png',
    pairPrice: '0.000007732',
    pairChange: '-6.85%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 113,
    name: 'LRC/SRM',
    quoteCurrency: 'SRM',
    check: false,
    BaseCurrency: 'LRC',
    pairImg: './Loopring(LRC).png',
    pairPrice: '0.00002928763',
    pairChange: '-6.77%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 114,
    name: 'CHIB/SRM',
    quoteCurrency: 'SRM',
    check: false,
    BaseCurrency: 'CHIB',
    pairImg: './SHIBAINU(SHIB).png',
    pairPrice: '0.00002073',
    pairChange: '+4.65%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 115,
    name: 'ADA/SRM',
    quoteCurrency: 'SRM',
    check: false,
    BaseCurrency: 'ADA',
    pairImg: './DerivaDAO(DDX).png',
    pairPrice: '0.0098774',
    pairChange: '-4.41%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 116,
    name: 'ROSE/SRM',
    quoteCurrency: 'SRM',
    check: false,
    BaseCurrency: 'ROSE',
    pairImg: './Rise(Rise).png',
    pairPrice: '0.000120984',
    pairChange: '-7.13%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 211,
    name: 'ETH/SOL',
    quoteCurrency: 'SOL',
    check: false,
    BaseCurrency: 'ETH',
    pairImg: './Ethereum(ETH).png',
    pairPrice: '0.000356',
    pairChange: '+1.81%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 212,
    name: 'AVAX/SOL',
    quoteCurrency: 'SOL',
    check: false,
    BaseCurrency: 'AVAX',
    pairImg: './Avalanche(AVAX).png',
    pairPrice: '0.000007732',
    pairChange: '-6.85%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 213,
    name: 'LRC/SOL',
    quoteCurrency: 'SOL',
    check: false,
    BaseCurrency: 'LRC',
    pairImg: './Loopring(LRC).png',
    pairPrice: '0.00002928763',
    pairChange: '-6.77%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 214,
    name: 'CHIB/SOL',
    quoteCurrency: 'SOL',
    check: false,
    BaseCurrency: 'CHIB',
    pairImg: './SHIBAINU(SHIB).png',
    pairPrice: '0.00002073',
    pairChange: '+4.65%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 215,
    name: 'ADA/SOL',
    quoteCurrency: 'SOL',
    check: false,
    BaseCurrency: 'ADA',
    pairImg: './DerivaDAO(DDX).png',
    pairPrice: '0.0098774',
    pairChange: '-4.41%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 216,
    name: 'ROSE/SOL',
    quoteCurrency: 'USDSOLT',
    check: false,
    BaseCurrency: 'ROSE',
    pairImg: './Rise(Rise).png',
    pairPrice: '0.000120984',
    pairChange: '-7.13%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 411,
    name: 'ETH/CNTRY',
    quoteCurrency: 'CNTRY',
    check: false,
    BaseCurrency: 'ETH',
    pairImg: './Ethereum(ETH).png',
    pairPrice: '0.000356',
    pairChange: '+1.81%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 412,
    name: 'AVAX/CNTRY',
    quoteCurrency: 'UCNTRYSDT',
    check: false,
    BaseCurrency: 'AVAX',
    pairImg: './Avalanche(AVAX).png',
    pairPrice: '0.000007732',
    pairChange: '-6.85%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 413,
    name: 'LRC/CNTRY',
    quoteCurrency: 'CNTRY',
    check: false,
    BaseCurrency: 'LRC',
    pairImg: './Loopring(LRC).png',
    pairPrice: '0.00002928763',
    pairChange: '-6.77%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 414,
    name: 'CHIB/CNTRY',
    quoteCurrency: 'CNTRY',
    check: false,
    BaseCurrency: 'CHIB',
    pairImg: './SHIBAINU(SHIB).png',
    pairPrice: '0.00002073',
    pairChange: '+4.65%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 415,
    name: 'ADA/CNTRY',
    quoteCurrency: 'CNTRY',
    check: false,
    BaseCurrency: 'ADA',
    pairImg: './DerivaDAO(DDX).png',
    pairPrice: '0.0098774',
    pairChange: '-4.41%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 416,
    name: 'ROSE/CNTRY',
    quoteCurrency: 'CNTRY',
    check: false,
    BaseCurrency: 'ROSE',
    pairImg: './Rise(Rise).png',
    pairPrice: '0.000120984',
    pairChange: '-7.13%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 511,
    name: 'ETH/BTC',
    quoteCurrency: 'BTC',
    check: false,
    BaseCurrency: 'ETH',
    pairImg: './Ethereum(ETH).png',
    pairPrice: '0.000356',
    pairChange: '+1.81%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 512,
    name: 'AVAX/BTC',
    quoteCurrency: 'BTC',
    check: false,
    BaseCurrency: 'AVAX',
    pairImg: './Avalanche(AVAX).png',
    pairPrice: '0.000007732',
    pairChange: '-6.85%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 513,
    name: 'LRC/BTC',
    quoteCurrency: 'BTC',
    check: false,
    BaseCurrency: 'LRC',
    pairImg: './Loopring(LRC).png',
    pairPrice: '0.00002928763',
    pairChange: '-6.77%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 514,
    name: 'CHIB/BTC',
    quoteCurrency: 'BTC',
    check: false,
    BaseCurrency: 'CHIB',
    pairImg: './SHIBAINU(SHIB).png',
    pairPrice: '0.00002073',
    pairChange: '+4.65%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 515,
    name: 'ADA/BTC',
    quoteCurrency: 'BTC',
    check: false,
    BaseCurrency: 'ADA',
    pairImg: './DerivaDAO(DDX).png',
    pairPrice: '0.0098774',
    pairChange: '-4.41%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 516,
    name: 'ROSE/BTC',
    quoteCurrency: 'BTC',
    check: false,
    BaseCurrency: 'ROSE',
    pairImg: './Rise(Rise).png',
    pairPrice: '0.000120984',
    pairChange: '-7.13%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 611,
    name: 'ETH/ETH',
    quoteCurrency: 'ETH',
    check: false,
    BaseCurrency: 'ETH',
    pairImg: './Ethereum(ETH).png',
    pairPrice: '0.000356',
    pairChange: '+1.81%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 612,
    name: 'AVAX/ETH',
    quoteCurrency: 'ETH',
    check: false,
    BaseCurrency: 'AVAX',
    pairImg: './Avalanche(AVAX).png',
    pairPrice: '0.000007732',
    pairChange: '-6.85%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 613,
    name: 'LRC/ETH',
    quoteCurrency: 'ETH',
    check: false,
    BaseCurrency: 'LRC',
    pairImg: './Loopring(LRC).png',
    pairPrice: '0.00002928763',
    pairChange: '-6.77%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 614,
    name: 'CHIB/ETH',
    quoteCurrency: 'ETH',
    check: false,
    BaseCurrency: 'CHIB',
    pairImg: './SHIBAINU(SHIB).png',
    pairPrice: '0.00002073',
    pairChange: '+4.65%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 615,
    name: 'ADA/ETH',
    quoteCurrency: 'ETH',
    check: false,
    BaseCurrency: 'ADA',
    pairImg: './DerivaDAO(DDX).png',
    pairPrice: '0.0098774',
    pairChange: '-4.41%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
  {
    pairId: 616,
    name: 'ROSE/ETH',
    quoteCurrency: 'ETH',
    check: false,
    BaseCurrency: 'ROSE',
    pairImg: './Rise(Rise).png',
    pairPrice: '0.000120984',
    pairChange: '-7.13%',
    star: false,
    deprecated: false,
    address: '',
    programId: '',
  },
];
